name: build
on: [ push ]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Checkout Codebase
        uses: actions/checkout@v1

      - name: Get Dependencies
        run: |
          go env -w GO111MODULE=auto
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Build
        run: |
          go build twitch_download_chat.go
          go build twitch_download_vod.go
          go build twitch_live_stream.go

      - name: Upload Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: twitch_vods_ubuntu.zip
          path: |
            config_example.json
            twitch_download_chat
            twitch_download_vod
            twitch_live_stream


