name: build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - name: Checkout Codebase
        uses: actions/checkout@v1

      - name: Get Dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Build
        run: |
          go build twitch_chat_live.go
          go build twitch_video_live.go

      - name: Upload Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: twitch_vods_ubuntu.zip
          path: |
            twitch_chat_live
            twitch_video_live


